import { digest } from '../core/binding.mjs';
const CONTROL_KEYS=new Set(['id','version','selector','denominator','evidence','families','lenses','providers','rules','scenarios','decisionMode','missingEvidenceEffect','claimLevels','remediationOwner','sourceConcepts','benchmark','provenance','stopShip','unimplemented']);
const PACK_KEYS=new Set(['id','version','class','dependencies','source','qualification','controls']);
const PACK_CLASSES=new Set(['universal','target','component','stack','environment','conditional','policy']);
const DECISIONS=new Set(['deterministic','measured','reasoning','human']);const EFFECTS=new Set(['unproven','fail','not-applicable']);const OWNERS=new Set(['code','design','writing','architecture','manual']);
const QUALIFICATIONS=new Set(['unproven','source-tested','measured']);
export function validateControl(control) { for(const key of Object.keys(control))if(!CONTROL_KEYS.has(key))throw new Error(`unknown control field: ${key}`);for (const key of ['id','version','selector','denominator','evidence','families','lenses','providers','rules','scenarios','decisionMode','missingEvidenceEffect','claimLevels','remediationOwner','sourceConcepts','stopShip','benchmark','provenance']) if (control[key] == null) throw new Error(`control missing ${key}`);for(const key of ['evidence','families','lenses','rules','scenarios','claimLevels','sourceConcepts'])if(!Array.isArray(control[key])||!control[key].length)throw new Error(`control ${key} must be a non-empty array`);if(!Array.isArray(control.providers))throw new Error('control providers must be an array');if(!control.selector||typeof control.selector!=='object'||Array.isArray(control.selector))throw new Error('control selector must be an object');if(new Set(control.claimLevels).size!==control.claimLevels.length)throw new Error(`duplicate control claim level: ${control.id}`);if(!DECISIONS.has(control.decisionMode)||!EFFECTS.has(control.missingEvidenceEffect)||!OWNERS.has(control.remediationOwner))throw new Error(`control policy enum invalid: ${control.id}`);if(typeof control.stopShip!=='boolean'||typeof control.benchmark!=='object'||!['unproven','source-tested','measured'].includes(control.benchmark.status)||typeof control.provenance!=='object'||!control.provenance.source||!Array.isArray(control.provenance.lineage))throw new Error(`control evidence contract invalid: ${control.id}`);return control; }
export function validatePack(pack) { for(const key of Object.keys(pack))if(!PACK_KEYS.has(key))throw new Error(`unknown control pack field: ${key}`);if (!pack.id || !pack.version || !Array.isArray(pack.controls)||!Array.isArray(pack.dependencies)||!PACK_CLASSES.has(pack.class)) throw new Error('invalid control pack');if(!pack.source||typeof pack.source!=='object'||Array.isArray(pack.source)||!pack.source.kind||!pack.source.rights)throw new Error('invalid control pack source');if(!QUALIFICATIONS.has(pack.qualification))throw new Error('invalid control pack qualification');const ids=new Set();for(const control of pack.controls){validateControl(control);if(ids.has(control.id))throw new Error(`duplicate control in pack: ${control.id}`);ids.add(control.id);}return pack; }
export function controlDigest(control) { return digest(validateControl(control)); }
