import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import { AuthorityBindingStore } from '../lib/authority-binding-store.mjs';
import { digestValue } from '../lib/canonical.mjs';
import { findCurrentAdvisoryJudgment, mintAdvisoryJudgment, persistAdvisoryJudgment, validateAdvisoryJudgmentCase, verifyAdvisoryJudgment } from '../lib/advisory-judgment.mjs';
import { generateTestKeyRing } from '../lib/keys.mjs';
import { ReceiptStore } from '../lib/receipt-store.mjs';

const now = '2026-08-14T00:00:00.000Z'; const d = (v) => digestValue(v);
const expected = { runId: 'run-judgment', taskId: 'AD-1', contractId: 'EC-ADVISORY-JUDGMENT-v1', contractVersion: 1, contractDigest: d('contract'), stateDigest: d('state'), sourceDigest: d('source'), sourceRevision: 'abcdef0' };
function wire() { const root = mkdtempSync(join(tmpdir(), 'arcane-judgment-')); const keyRing = generateTestKeyRing(['host']); const bindings = new AuthorityBindingStore({ root: join(root, 'bindings'), clock: () => now }); bindings.observe({ adapter: 'codex', sessionId: 'sage', agentId: 'sage-agent', agentType: 'sage', eventId: 'hev-sage' }); bindings.observe({ adapter: 'codex', sessionId: 'oracle', agentId: 'oracle-agent', agentType: 'oracle', eventId: 'hev-oracle' }); return { root, keyRing, bindings, options: { keyRing, keyId: 'host', authorityBindingStore: bindings, clock: () => now, now: new Date('2026-08-14T00:01:00.000Z') } }; }
function receipt(w, role, reviewOfReceiptDigest = null) { return mintAdvisoryJudgment({ role, ...expected, judgment: { subjectDigest: d('subject'), disposition: 'ACCEPT', rationaleDigest: d(role) }, reviewOfReceiptDigest, adapter: 'codex', sessionId: role }, w.options); }
test('host-derived Sage/Oracle records bind exact execution, state & source', () => { const w = wire(); try { const sage = receipt(w, 'sage'); assert.equal(verifyAdvisoryJudgment(sage, expected, w.options).allowed, true); assert.equal(sage.authority, 'sage'); assert.throws(() => mintAdvisoryJudgment({ role: 'sage', ...expected, judgment: sage.judgment, reviewOfReceiptDigest: null, adapter: 'codex', sessionId: 'sage', agentIdDigest: d('forged') }, w.options), (e) => e.code === 'ARC_AUTHORITY_MODEL_CLAIMED'); assert.equal(verifyAdvisoryJudgment({ ...sage, sourceDigest: d('forged') }, expected, w.options).code, 'ARC_AUTH_FORGED'); } finally { rmSync(w.root, { recursive: true, force: true }); } });
test('persistence rejects replay & query requires fresh independent Oracle review', () => { const w = wire(); try { const store = new ReceiptStore({ root: join(w.root, 'receipts') }); const sage = receipt(w, 'sage'); const oracle = receipt(w, 'oracle', d(sage)); assert.equal(persistAdvisoryJudgment(sage, { receiptStore: store, ...w.options }).allowed, true); assert.equal(persistAdvisoryJudgment(sage, { receiptStore: store, ...w.options }).code, 'ARC_REPLAY_NONCE_SEEN'); assert.equal(persistAdvisoryJudgment(oracle, { receiptStore: store, ...w.options }).allowed, true); assert.equal(findCurrentAdvisoryJudgment({ receiptStore: store, expected }, w.options).allowed, true); const self = { ...oracle, agentIdDigest: sage.agentIdDigest }; assert.equal(findCurrentAdvisoryJudgment({ receiptStore: { verifyChain: () => ({ ok: true }), list: () => [sage, self] }, expected }, w.options).code, 'ARC_EVIDENCE_INSUFFICIENT'); assert.equal(verifyAdvisoryJudgment(sage, expected, { ...w.options, now: new Date('2026-08-16T00:00:00.000Z') }).code, 'ARC_REPLAY_STALE'); } finally { rmSync(w.root, { recursive: true, force: true }); } });
test('Oracle persistence requires a fresh independent Sage review with same execution, state, source & judgment', () => { const w = wire(); try { const store = new ReceiptStore({ root: join(w.root, 'receipts') }); const sage = receipt(w, 'sage'); assert.equal(persistAdvisoryJudgment(sage, { receiptStore: store, ...w.options }).allowed, true); const input = { role: 'oracle', ...expected, judgment: { subjectDigest: d('subject'), disposition: 'REJECT', rationaleDigest: d('oracle-reject') }, reviewOfReceiptDigest: d(sage), adapter: 'codex', sessionId: 'oracle' }; const wrongVerdict = mintAdvisoryJudgment(input, w.options); assert.equal(persistAdvisoryJudgment(wrongVerdict, { receiptStore: store, ...w.options }).code, 'ARC_BINDING_MISMATCH'); const wrongState = mintAdvisoryJudgment({ ...input, judgment: { ...input.judgment, disposition: 'ACCEPT' }, stateDigest: d('other-state') }, w.options); assert.equal(persistAdvisoryJudgment(wrongState, { receiptStore: store, ...w.options }).code, 'ARC_BINDING_MISMATCH'); const unlinked = mintAdvisoryJudgment({ ...input, judgment: { ...input.judgment, disposition: 'ACCEPT' }, reviewOfReceiptDigest: d('absent-sage') }, w.options); assert.equal(persistAdvisoryJudgment(unlinked, { receiptStore: store, ...w.options }).code, 'ARC_BINDING_MISMATCH'); } finally { rmSync(w.root, { recursive: true, force: true }); } });
test('structured case validator has no prose or case-id pass path', () => { const valid = { case: 'any-id', expected: { ...expected, subjectDigest: d('subject'), disposition: 'ACCEPT' }, sage: { role: 'sage', adapter: 'codex', sessionId: 's', judgment: { subjectDigest: d('subject'), disposition: 'ACCEPT', rationaleDigest: d('r1') }, review: null }, oracle: { role: 'oracle', adapter: 'codex', sessionId: 'o', judgment: { subjectDigest: d('subject'), disposition: 'ACCEPT', rationaleDigest: d('r2') }, review: 'sage' } }; assert.equal(validateAdvisoryJudgmentCase(valid), true); assert.equal(validateAdvisoryJudgmentCase({ ...valid, expected: { ...valid.expected, stateDigest: 'state' } }), false); assert.equal(validateAdvisoryJudgmentCase({ ...valid, oracle: { ...valid.oracle, judgment: { ...valid.oracle.judgment, subjectDigest: d('other') } } }), false); assert.equal(validateAdvisoryJudgmentCase({ ...valid, oracle: { ...valid.oracle, judgment: { ...valid.oracle.judgment, disposition: 'REJECT' } } }), false); } );
