// Codex harness binding: four [agents.*] projections of Legion's engineering
// doctrine (sage, alchemist, oracle, covenant-seat) plus an [mcp_servers.legion]
// entry that points at the packaged stdio MCP server. The Codex side loads
// `.codex/agents/<name>.toml` per-agent and merges `.codex/config.toml`
// globally — both are owned by Legion when the marker is present.
//
// The agent TOML files are fully authored by Legion on every run (they are
// not user-edited) and use writeIfDifferent for atomic idempotency. The
// shared `.codex/config.toml` is marker-managed via stdlib line surgery:
// only the exact Legion [agents.*] tables and the [mcp_servers.legion]
// table are inside the marker; everything else is the user's file and is
// preserved byte-for-byte. Unknown tables are reported as managed_conflict
// and never overwritten.

import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { roleProjection } from '../../../roster/index.mjs';
import { doctrineText } from './doctrine.mjs';
import { writeIfDifferent } from './common.mjs';
import { loadNamingRegistry } from '../../../naming/registry.mjs';
import { isLegionOwnedAssuranceBinding } from '../../../naming/migrations.mjs';
import {
  upsertManagedBlock,
  hasManagedMarker,
  TOML_MANAGED_MARKER,
  tomlBasicString,
  LEGION_OWNED_TOML_HEADERS,
} from './toml-managed-block.mjs';

export const NAME = 'codex';
export const FIDELITY_TIER = 'full';

// QUARANTINED as an auto-selected installer (host/runtime cleanup, 2026-08-20).
//
// The descriptor-driven harness seam (src/lib/host/) is now the installer for
// this harness's .codex/config.toml MCP registration. Two installers competing for one surface is the
// failure the one-installation-owner invariant forbids and the precedent already applied to bind's Claude
// Code writer. `detect()` therefore returns false: `legion bind --write` with no
// explicit --harness will never select this writer.
//
// It is QUARANTINED rather than deleted because it still carries the legacy
// migration paths the seam does not have (prior-generation unmanaged-table migration and duplicate-MCP cleanup). Those run only when the
// operator asks for this harness by name. New installations use
// `legion harness install codex`.
export const QUARANTINED = true;
export const QUARANTINE_NOTE =
  'legion bind no longer auto-selects codex; the harness adapter seam installs it '
  + '(legion harness install codex). This writer remains reachable only via an explicit '
  + '--harness codex, for its legacy migration paths.';


const AGENTS_DIR = '.codex/agents';
const CONFIG_PATH = '.codex/config.toml';

const AGENT_PROJECTIONS = Object.freeze([
  { file: 'sage.toml', name: 'sage', role: 'sage' },
  { file: 'alchemist.toml', name: 'alchemist', role: 'alchemist' },
  { file: 'oracle.toml', name: 'oracle', role: 'oracle' },
  { file: 'covenant-seat.toml', name: 'covenant-seat', doctrineFile: 'covenant-seat.md' },
]);

function readDoctrineFrontmatter(doctrineBody) {
  const lines = doctrineBody.split(/\r?\n/);
  if (!lines[0] || lines[0].trim() !== '---') return { description: null };
  let description = null;
  for (let i = 1; i < lines.length; i++) {
    if (lines[i].trim() === '---') break;
    const m = /^description:\s*(.*)$/.exec(lines[i]);
    if (m) description = m[1].trim();
  }
  return { description };
}

function agentToml(name, doctrineBody) {
  const out = [];
  out.push(`# Generated by Legion bind. Do not edit; re-run \`legion bind --write\`.`);
  out.push(`name = ${tomlBasicString(name)}`);
  out.push(`developer_instructions = ${tomlBasicString(doctrineBody)}`);
  out.push('');
  return out.join('\n');
}

function packagedServerPath() {
  const here = fileURLToPath(import.meta.url);
  return join(dirname(here), '..', '..', '..', '..', 'integrations', 'mcp', 'server.mjs');
}

function mcpServersLegionInner() {
  const server = packagedServerPath().replace(/\\/g, '/');
  const escaped = server.replace(/"/g, '\\"');
  return [
    '# Legion MCP server entry (packaged). command = current Node; args = absolute',
    '# path to the stdio server shipped inside this Legion package.',
    '[mcp_servers.legion]',
    'command = "node"',
    `args = ["${escaped}"]`,
    '',
  ].join('\n');
}

function sourceText(projection) { return projection.role ? roleProjection(projection.role) : doctrineText(projection.doctrineFile); }

function configInnerToml() {
  const tables = AGENT_PROJECTIONS.map((p) => `[agents.${p.name}]\ndescription = ${tomlBasicString(readDoctrineFrontmatter(sourceText(p)).description ?? "")}\nconfig_file = ${tomlBasicString(`agents/${p.file}`)}\n`).join('\n');
  return `${tables}\n${mcpServersLegionInner()}`;
}

function generatedHeader() {
  return `# Generated by Legion bind.\n# Owned keys: ${LEGION_OWNED_TOML_HEADERS.join(', ')}.\n# Everything outside the legion:managed-block markers below is the user's file.`;
}

const LEGACY_HEADERS = new Set([
  ...Object.keys(loadNamingRegistry().authorities).map((id) => `[agents.${id}]`),
  ...Object.values(loadNamingRegistry().authorities).flatMap(({ aliases = [] }) => aliases.map(({ id }) => `[agents.${id}]`)),
  '[agents.covenant-seat]', '[mcp_servers.legion]',
]);

function parseTomlString(value) {
  try { return JSON.parse(value); } catch { return null; }
}

function assuranceTableMigration(existing) {
  const legacyId = Object.values(loadNamingRegistry().authorities)
    .find(({ displayName }) => displayName === 'Oracle')?.aliases?.[0]?.id;
  if (!legacyId) return { content: existing, conflicts: [] };
  const targetHeader = `[mcp_servers.${legacyId}]`;
  const lines = existing.split(/\r?\n/);
  const tables = [];
  let inManaged = false;
  for (let index = 0; index < lines.length; index++) {
    if (lines[index].includes(TOML_MANAGED_MARKER.HEADER_PREFIX)) inManaged = true;
    if (lines[index].includes(TOML_MANAGED_MARKER.HEADER_SUFFIX)) { inManaged = false; continue; }
    const header = /^\s*(\[[^\]]+\])/.exec(lines[index])?.[1];
    if (header !== targetHeader || inManaged) continue;
    let end = index + 1;
    while (end < lines.length && !/^\s*\[[^\]]+\]/.test(lines[end]) && !lines[end].includes(TOML_MANAGED_MARKER.HEADER_PREFIX)) end++;
    tables.push({ start: index, end, body: lines.slice(index + 1, end) });
    index = end - 1;
  }
  if (!tables.length) return { content: existing, conflicts: [] };
  const classified = tables.map((table) => {
    const commandLine = table.body.find((line) => /^\s*command\s*=/.test(line));
    const argsLine = table.body.find((line) => /^\s*args\s*=/.test(line));
    const command = commandLine ? parseTomlString(commandLine.slice(commandLine.indexOf('=') + 1).trim()) : null;
    const args = argsLine ? parseTomlString(argsLine.slice(argsLine.indexOf('=') + 1).trim()) : null;
    return { ...table, owned: isLegionOwnedAssuranceBinding({ command, args }) };
  });
  const unowned = classified.filter(({ owned }) => !owned);
  if (unowned.length) {
    return { content: existing, conflicts: unowned.map(() => ({ header: targetHeader, kind: 'legacy_assurance_binding_not_legion_owned' })) };
  }
  const removed = new Set(classified.flatMap(({ start, end }) => Array.from({ length: end - start }, (_, offset) => start + offset)));
  return { content: lines.filter((_, index) => !removed.has(index)).join('\n').replace(/\n{3,}/g, '\n\n'), conflicts: [] };
}

function migrateLegacyConfig(raw) {
  const assurance = assuranceTableMigration(raw);
  if (assurance.conflicts.length) return assurance;
  const existing = assurance.content;
  const managed = hasManagedMarker(existing);
  const legionMcpCount = existing.split(/\r?\n/).filter((line) => line.trim() === '[mcp_servers.legion]').length;
  const legacyAgentPattern = new RegExp(`^\\[agents\\.(${Object.values(loadNamingRegistry().authorities).flatMap(({ aliases = [] }) => aliases.map(({ id }) => id)).join('|')})\\]\\s*$`, 'm');
  const generatedOwner = !managed
    && existing.includes('# Generated by Legion bind.')
    && [...LEGACY_HEADERS].some((header) => existing.split(/\r?\n/).some((line) => line.trim() === header));
  if ((!managed && !legacyAgentPattern.test(existing) && !generatedOwner) || (managed && legionMcpCount < 2)) return { content: existing, conflicts: [] };
  const kept = [];
  let dropping = false;
  let inManagedBlock = false;
  for (const line of existing.split(/\r?\n/)) {
    if (line.includes(TOML_MANAGED_MARKER.HEADER_PREFIX)) inManagedBlock = true;
    if (line.includes(TOML_MANAGED_MARKER.HEADER_SUFFIX)) {
      inManagedBlock = false;
      dropping = false;
      kept.push(line);
      continue;
    }
    const header = /^\s*(\[[^\]]+\])/.exec(line)?.[1] ?? null;
    if (header) dropping = !inManagedBlock && (managed ? header === '[mcp_servers.legion]' : LEGACY_HEADERS.has(header));
    if (!dropping) kept.push(line);
  }
  let content = kept.join('\n');
  if (generatedOwner) content = content.replace(/(?:^|\n)# Generated by Legion bind\.\n# Owned keys:[^\n]*\n?/, '\n');
  return { content: content.replace(/\n{3,}/g, '\n\n').replace(/^\n|\s+$/g, '') + '\n', conflicts: [] };
}

function agentFileTarget(root, projection) {
  return {
    path: join(root, AGENTS_DIR, projection.file),
    kind: 'whole',
    reason: `install ${projection.name} agent projection under .codex/agents/`,
    content: agentToml(projection.name, sourceText(projection)),
  };
}

function configTarget(root) {
  const path = join(root, CONFIG_PATH);
  const raw = existsSync(path) ? readFileSync(path, 'utf8') : '';
  const migration = migrateLegacyConfig(raw);
  if (migration.conflicts.length) {
    return { path, kind: 'toml-managed', reason: 'install Legion agent projections and MCP entry in .codex/config.toml', result: { status: 'managed_conflict', conflicts: migration.conflicts, content: raw } };
  }
  const existing = migration.content;
  const inner = configInnerToml();
  const planned = upsertManagedBlock(existing, generatedHeader(), inner);
  const result = planned.status === 'managed_conflict'
    ? { ...planned, content: raw }
    : raw !== existing && planned.status === 'unchanged'
    ? { ...planned, status: 'replaced' }
    : planned;
  return { path, kind: 'toml-managed', reason: 'install Legion agent projections and MCP entry in .codex/config.toml', result };
}

// Never auto-selected — see the quarantine note above.
export function detect() {
  return false;
}

/** Whether a Codex checkout is present at all; used only for reporting. */
export function present(root) {
  return existsSync(join(root, '.codex')) || existsSync(join(root, AGENTS_DIR));
}

export function targets(root) {
  return [...AGENT_PROJECTIONS.map((p) => agentFileTarget(root, p)), configTarget(root)];
}

export function plan(root) {
  return targets(root).map(({ path, reason }) => ({ path, reason }));
}

export function write(root) {
  const wrote = [];
  const managedConflicts = [];
  const planned = targets(root);
  for (const target of planned) {
    if (target.kind === 'toml-managed' && target.result.status === 'managed_conflict') {
      managedConflicts.push({ path: target.path, conflicts: target.result.conflicts });
    }
  }
  if (managedConflicts.length) return { wrote, wouldWrite: [], managedConflicts };
  for (const target of planned) {
    if (target.kind === 'whole') {
      writeIfDifferent(target.path, target.content);
      wrote.push(target.path);
    } else if (target.kind === 'toml-managed') {
      if (target.result.status === 'unchanged') continue;
      writeIfDifferent(target.path, target.result.content);
      wrote.push(target.path);
    }
  }
  return { wrote, wouldWrite: [], managedConflicts };
}

export function buildAgentToml(name, doctrineBody) {
  return agentToml(name, doctrineBody);
}
