[package]
name = "legion-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
legion-catalog = { path = "../legion-catalog" }
legion-contracts = { path = "../legion-contracts" }
legion-policy = { path = "../legion-policy" }
legion-provider-sdk = { path = "../legion-provider-sdk" }
serde.workspace = true
tokio.workspace = true
tokio-util.workspace = true
