[package]
name = "legion-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
legion-catalog = { path = "../legion-catalog" }
legion-contracts = { path = "../legion-contracts" }
legion-policy = { path = "../legion-policy" }
legion-provider-sdk = { path = "../legion-provider-sdk" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
hex.workspace = true
regex.workspace = true
reqwest = { workspace = true, features = ["blocking"] }
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
zip.workspace = true
headless_chrome.workspace = true
image.workspace = true
scraper.workspace = true
libc.workspace = true
