use super::{io_error, CommandError, CommandResult};
use clap::{Args, Subcommand, ValueEnum};
use serde_json::json;
use std::path::PathBuf;

/// Native machine setup is intentionally a small grammar over the frozen host
/// registry: previews are materialized as files, then mutations require that
/// exact preview plus an explicit confirmation flag.
#[derive(Debug, Args)]
pub struct SetupArgs {
    #[command(subcommand)]
    command: Option<SetupCommand>,
}

#[derive(Debug, Subcommand)]
enum SetupCommand {
    Preview(SetupPreviewArgs),
    Apply(SetupMutationArgs),
    Status(SetupStatusArgs),
    Repair(SetupMutationArgs),
    Disable(SetupMutationArgs),
    Remove(SetupMutationArgs),
    Purge(SetupMutationArgs),
}

#[derive(Clone, Debug, ValueEnum)]
enum SetupActionArg {
    Apply,
    Repair,
    Disable,
    Remove,
    Purge,
}

impl From<SetupActionArg> for legion_host::SetupAction {
    fn from(action: SetupActionArg) -> Self {
        match action {
            SetupActionArg::Apply => Self::Apply,
            SetupActionArg::Repair => Self::Repair,
            SetupActionArg::Disable => Self::Disable,
            SetupActionArg::Remove => Self::Remove,
            SetupActionArg::Purge => Self::Purge,
        }
    }
}

#[derive(Debug, Args)]
struct SetupPreviewArgs {
    /// Lifecycle action to plan. Preview itself never mutates state.
    #[arg(long, value_enum, default_value_t = SetupActionArg::Apply)]
    action: SetupActionArg,
    #[command(flatten)]
    request: SetupRequestArgs,
    /// Optional durable JSON plan file for a later explicit mutation.
    #[arg(long)]
    out: Option<PathBuf>,
}

#[derive(Debug, Args)]
struct SetupRequestArgs {
    /// JSON BoundRelease document from installed, verified release assets.
    #[arg(long)]
    release: PathBuf,
    /// JSON array of ClientEvidence collected by the installed launcher.
    #[arg(long = "client-evidence")]
    client_evidence: Option<PathBuf>,
    /// Restrict a preview to one supported client; default is all supported clients.
    #[arg(long)]
    client: Option<String>,
    /// Ask the host to keep the planned operation dry-run only.
    #[arg(long)]
    dry_run: bool,
}

#[derive(Debug, Args)]
struct SetupStatusArgs {
    #[command(flatten)]
    open: SetupOpenArgs,
}

#[derive(Debug, Args)]
struct SetupOpenArgs {
    /// JSON BoundRelease document from installed, verified release assets.
    #[arg(long)]
    release: PathBuf,
    /// Restrict status to one supported client; default is all supported clients.
    #[arg(long)]
    client: Option<String>,
}

#[derive(Debug, Args)]
struct SetupMutationArgs {
    /// JSON SetupPreview generated by `legion setup preview`.
    #[arg(long)]
    plan: PathBuf,
    /// Explicitly confirm the plan ID and digest recorded in --plan.
    #[arg(long)]
    confirm: bool,
}

pub fn run(args: SetupArgs) -> CommandResult {
    match args.command {
        Some(SetupCommand::Preview(args)) => preview(args),
        Some(SetupCommand::Apply(args)) => execute(args, legion_host::SetupAction::Apply),
        Some(SetupCommand::Status(args)) => status(args),
        Some(SetupCommand::Repair(args)) => execute(args, legion_host::SetupAction::Repair),
        Some(SetupCommand::Disable(args)) => execute(args, legion_host::SetupAction::Disable),
        Some(SetupCommand::Remove(args)) => execute(args, legion_host::SetupAction::Remove),
        Some(SetupCommand::Purge(args)) => execute(args, legion_host::SetupAction::Purge),
        None => Err(CommandError::usage(
            "legion setup requires preview, apply, status, repair, disable, remove, or purge",
        )),
    }
}

fn preview(args: SetupPreviewArgs) -> CommandResult {
    let request = request(args.request, args.action.into())?;
    let mut registry = open_registry(&request)?;
    let recovery = registry.recover().map_err(setup_error)?;
    let preview = registry.preview(request).map_err(setup_error)?;
    if let Some(path) = args.out {
        write_json(&path, &preview)?;
    }
    Ok(json!({
        "schemaVersion": 1,
        "kind": "legion-setup-preview",
        "status": "complete",
        "recovery": recovery,
        "preview": preview,
    }))
}

fn status(args: SetupStatusArgs) -> CommandResult {
    let open = args.open;
    let release = read_json(&open.release, "BoundRelease")?;
    let selector = selector(open.client);
    let mut registry = legion_host::SetupRegistry::open_platform(release).map_err(setup_error)?;
    let recovery = registry.recover().map_err(setup_error)?;
    let clients = registry.status(&selector).map_err(setup_error)?;
    Ok(json!({
        "schemaVersion": 1,
        "kind": "legion-setup-status",
        "status": "complete",
        "recovery": recovery,
        "clients": clients,
    }))
}

fn execute(args: SetupMutationArgs, expected: legion_host::SetupAction) -> CommandResult {
    if !args.confirm {
        return Err(CommandError::usage(
            "setup mutation requires --confirm for the exact supplied --plan",
        ));
    }
    let preview: legion_host::SetupPreview = read_json(&args.plan, "SetupPreview")?;
    if preview.request.action != expected {
        return Err(CommandError::usage(
            "setup command does not match the action recorded in --plan",
        ));
    }
    let mut registry = open_registry(&preview.request)?;
    let recovery = registry.recover().map_err(setup_error)?;
    let confirmation = legion_host::PlanConfirmation {
        plan_id: preview.plan_id.clone(),
        plan_digest: preview.plan_digest.clone(),
    };
    let confirmed = registry
        .confirm(preview, confirmation)
        .map_err(setup_error)?;
    let execution = registry.execute(confirmed).map_err(setup_error)?;
    Ok(json!({
        "schemaVersion": 1,
        "kind": "legion-setup-execution",
        "status": "complete",
        "recovery": recovery,
        "execution": execution,
    }))
}

fn request(
    args: SetupRequestArgs,
    action: legion_host::SetupAction,
) -> Result<legion_host::SetupRequest, CommandError> {
    Ok(legion_host::SetupRequest {
        action,
        selector: selector(args.client),
        release: read_json(&args.release, "BoundRelease")?,
        platform_state_root: legion_host::platform_state_root().map_err(setup_error)?,
        client_evidence: match args.client_evidence {
            Some(path) => read_json(&path, "ClientEvidence array")?,
            None => Vec::new(),
        },
        dry_run: args.dry_run,
    })
}

fn open_registry(
    request: &legion_host::SetupRequest,
) -> Result<legion_host::SetupRegistry<legion_host::OnDiskSetupStore>, CommandError> {
    legion_host::SetupRegistry::open_platform(request.release.clone()).map_err(setup_error)
}

fn selector(client: Option<String>) -> legion_host::ClientSelector {
    client
        .filter(|client| !client.trim().is_empty())
        .map(legion_host::ClientSelector::ClientId)
        .unwrap_or(legion_host::ClientSelector::AllSupported)
}

fn read_json<T: serde::de::DeserializeOwned>(
    path: &PathBuf,
    kind: &str,
) -> Result<T, CommandError> {
    let bytes = std::fs::read(path).map_err(io_error)?;
    serde_json::from_slice(&bytes).map_err(|error| {
        CommandError::usage(format!("invalid {kind} at {}: {error}", path.display()))
    })
}

fn write_json<T: serde::Serialize>(path: &PathBuf, value: &T) -> Result<(), CommandError> {
    let bytes = serde_json::to_vec_pretty(value).map_err(io_error)?;
    std::fs::write(path, bytes).map_err(io_error)
}

fn setup_error(error: legion_host::SetupError) -> CommandError {
    CommandError::incomplete(format!("{:?}: {}", error.code, error.remediation))
}
