// Codex harness binding: four [agents.*] projections of Legion's engineering
// doctrine (sage, alchemist, seer, covenant-seat) plus an [mcp_servers.legion]
// entry that points at the packaged stdio MCP server. The Codex side loads
// `.codex/agents/<name>.toml` per-agent and merges `.codex/config.toml`
// globally — both are owned by Legion when the marker is present.
//
// The agent TOML files are fully authored by Legion on every run (they are
// not user-edited) and use writeIfDifferent for atomic idempotency. The
// shared `.codex/config.toml` is marker-managed via stdlib line surgery:
// only the exact Legion [agents.*] tables and the [mcp_servers.legion]
// table are inside the marker; everything else is the user's file and is
// preserved byte-for-byte. Unknown tables are reported as managed_conflict
// and never overwritten.

import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { doctrineText } from './doctrine.mjs';
import { writeIfDifferent } from './common.mjs';
import {
  upsertManagedBlock,
  tomlBasicString,
  LEGION_OWNED_TOML_HEADERS,
} from './toml-managed-block.mjs';

export const NAME = 'codex';
export const FIDELITY_TIER = 'full';

const AGENTS_DIR = '.codex/agents';
const CONFIG_PATH = '.codex/config.toml';

const AGENT_PROJECTIONS = Object.freeze([
  { file: 'sage.toml', name: 'sage', doctrineFile: 'sage.md', model: 'gpt-5.6-sol', modelReasoningEffort: 'high' },
  { file: 'alchemist.toml', name: 'alchemist', doctrineFile: 'alchemist.md', model: 'gpt-5.6-terra', modelReasoningEffort: 'medium' },
  { file: 'seer.toml', name: 'seer', doctrineFile: 'seer.md', model: 'gpt-5.6-sol', modelReasoningEffort: 'high' },
  { file: 'covenant-seat.toml', name: 'covenant-seat', doctrineFile: 'covenant-seat.md', model: 'gpt-5.6-terra', modelReasoningEffort: 'medium' },
]);

function readDoctrineFrontmatter(doctrineBody) {
  const lines = doctrineBody.split(/\r?\n/);
  if (!lines[0] || lines[0].trim() !== '---') return { description: null };
  let description = null;
  for (let i = 1; i < lines.length; i++) {
    if (lines[i].trim() === '---') break;
    const m = /^description:\s*(.*)$/.exec(lines[i]);
    if (m) description = m[1].trim();
  }
  return { description };
}

function agentToml(name, model, modelReasoningEffort, doctrineBody) {
  const out = [];
  out.push(`# Generated by Legion bind (doctrine/${name}.md). Do not edit; re-run \`legion bind --write\`.`);
  out.push(`developer_instructions = ${tomlBasicString(doctrineBody)}`);
  out.push(`model = ${tomlBasicString(model)}`);
  out.push(`model_reasoning_effort = ${tomlBasicString(modelReasoningEffort)}`);
  out.push('');
  return out.join('\n');
}

function packagedServerPath() {
  const here = fileURLToPath(import.meta.url);
  return join(here, '..', '..', '..', '..', 'integrations', 'mcp', 'server.mjs');
}

function mcpServersLegionInner() {
  const server = packagedServerPath().replace(/\\/g, '/');
  const escaped = server.replace(/"/g, '\\"');
  return [
    '# Legion MCP server entry (packaged). command = current Node; args = absolute',
    '# path to the stdio server shipped inside this Legion package.',
    '[mcp_servers.legion]',
    'command = "node"',
    `args = ["${escaped}"]`,
    '',
  ].join('\n');
}

function configInnerToml() {
  const tables = AGENT_PROJECTIONS.map((p) => `[agents.${p.name}]\ndescription = ${tomlBasicString(readDoctrineFrontmatter(doctrineText(p.doctrineFile)).description ?? "")}\nconfig_file = ${tomlBasicString(`agents/${p.file}`)}\n`).join('\n');
  return `${tables}\n${mcpServersLegionInner()}`;
}

function generatedHeader() {
  return `# Generated by Legion bind.\n# Owned keys: ${LEGION_OWNED_TOML_HEADERS.join(', ')}.\n# Everything outside the legion:managed-block markers below is the user's file.`;
}

function agentFileTarget(root, projection) {
  return {
    path: join(root, AGENTS_DIR, projection.file),
    kind: 'whole',
    reason: `install ${projection.name} agent projection under .codex/agents/`,
    content: agentToml(projection.name, projection.model, projection.modelReasoningEffort, doctrineText(projection.doctrineFile)),
  };
}

function configTarget(root) {
  const path = join(root, CONFIG_PATH);
  const existing = existsSync(path) ? readFileSync(path, 'utf8') : '';
  const inner = configInnerToml();
  const result = upsertManagedBlock(existing, generatedHeader(), inner);
  return { path, kind: 'toml-managed', reason: 'install Legion agent projections and MCP entry in .codex/config.toml', result };
}

export function detect(root) {
  return existsSync(join(root, 'AGENTS.md')) || existsSync(join(root, '.codex')) || existsSync(join(root, AGENTS_DIR));
}

export function targets(root) {
  return [...AGENT_PROJECTIONS.map((p) => agentFileTarget(root, p)), configTarget(root)];
}

export function plan(root) {
  return targets(root).map(({ path, reason }) => ({ path, reason }));
}

export function write(root) {
  const wrote = [];
  const managedConflicts = [];
  for (const target of targets(root)) {
    if (target.kind === 'whole') {
      writeIfDifferent(target.path, target.content);
      wrote.push(target.path);
    } else if (target.kind === 'toml-managed') {
      if (target.result.status === 'managed_conflict') {
        managedConflicts.push({ path: target.path, conflicts: target.result.conflicts });
        continue;
      }
      if (target.result.status === 'unchanged') continue;
      writeIfDifferent(target.path, target.result.content);
      wrote.push(target.path);
    }
  }
  return { wrote, wouldWrite: [], managedConflicts };
}

export function buildAgentToml(name, model, modelReasoningEffort, doctrineBody) {
  return agentToml(name, model, modelReasoningEffort, doctrineBody);
}
