// Codex harness binding: four [agents.*] projections of Legion's engineering
// doctrine (sage, alchemist, oracle, covenant-seat) plus an [mcp_servers.legion]
// entry that points at the packaged stdio MCP server. The Codex side loads
// `.codex/agents/<name>.toml` per-agent and merges `.codex/config.toml`
// globally — both are owned by Legion when the marker is present.
//
// The agent TOML files are fully authored by Legion on every run (they are
// not user-edited) and use writeIfDifferent for atomic idempotency. The
// shared `.codex/config.toml` is marker-managed via stdlib line surgery:
// only the exact Legion [agents.*] tables and the [mcp_servers.legion]
// table are inside the marker; everything else is the user's file and is
// preserved byte-for-byte. Unknown tables are reported as managed_conflict
// and never overwritten.

import { existsSync, readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { roleProjection } from '../../../roster/index.mjs';
import { doctrineText } from './doctrine.mjs';
import { writeIfDifferent } from './common.mjs';
import {
  upsertManagedBlock,
  hasManagedMarker,
  TOML_MANAGED_MARKER,
  tomlBasicString,
  LEGION_OWNED_TOML_HEADERS,
} from './toml-managed-block.mjs';

export const NAME = 'codex';
export const FIDELITY_TIER = 'full';

const AGENTS_DIR = '.codex/agents';
const CONFIG_PATH = '.codex/config.toml';

const AGENT_PROJECTIONS = Object.freeze([
  { file: 'sage.toml', name: 'sage', role: 'sage' },
  { file: 'alchemist.toml', name: 'alchemist', role: 'alchemist' },
  { file: 'oracle.toml', name: 'oracle', role: 'oracle' },
  { file: 'covenant-seat.toml', name: 'covenant-seat', doctrineFile: 'covenant-seat.md' },
]);

function readDoctrineFrontmatter(doctrineBody) {
  const lines = doctrineBody.split(/\r?\n/);
  if (!lines[0] || lines[0].trim() !== '---') return { description: null };
  let description = null;
  for (let i = 1; i < lines.length; i++) {
    if (lines[i].trim() === '---') break;
    const m = /^description:\s*(.*)$/.exec(lines[i]);
    if (m) description = m[1].trim();
  }
  return { description };
}

function agentToml(name, doctrineBody) {
  const out = [];
  out.push(`# Generated by Legion bind. Do not edit; re-run \`legion bind --write\`.`);
  out.push(`name = ${tomlBasicString(name)}`);
  out.push(`developer_instructions = ${tomlBasicString(doctrineBody)}`);
  out.push('');
  return out.join('\n');
}

function packagedServerPath() {
  const here = fileURLToPath(import.meta.url);
  return join(dirname(here), '..', '..', '..', '..', 'integrations', 'mcp', 'server.mjs');
}

function mcpServersLegionInner() {
  const server = packagedServerPath().replace(/\\/g, '/');
  const escaped = server.replace(/"/g, '\\"');
  return [
    '# Legion MCP server entry (packaged). command = current Node; args = absolute',
    '# path to the stdio server shipped inside this Legion package.',
    '[mcp_servers.legion]',
    'command = "node"',
    `args = ["${escaped}"]`,
    '',
  ].join('\n');
}

function sourceText(projection) { return projection.role ? roleProjection(projection.role) : doctrineText(projection.doctrineFile); }

function configInnerToml() {
  const tables = AGENT_PROJECTIONS.map((p) => `[agents.${p.name}]\ndescription = ${tomlBasicString(readDoctrineFrontmatter(sourceText(p)).description ?? "")}\nconfig_file = ${tomlBasicString(`agents/${p.file}`)}\n`).join('\n');
  return `${tables}\n${mcpServersLegionInner()}`;
}

function generatedHeader() {
  return `# Generated by Legion bind.\n# Owned keys: ${LEGION_OWNED_TOML_HEADERS.join(', ')}.\n# Everything outside the legion:managed-block markers below is the user's file.`;
}

const LEGACY_HEADERS = new Set([
  '[agents.sage]', '[agents.alchemist]', '[agents.seer]',
  '[agents.oracle]', '[agents.covenant-seat]', '[mcp_servers.legion]',
]);

function migrateLegacyConfig(existing) {
  const managed = hasManagedMarker(existing);
  const legionMcpCount = existing.split(/\r?\n/).filter((line) => line.trim() === '[mcp_servers.legion]').length;
  if ((!managed && !/^\[agents\.seer\]\s*$/m.test(existing)) || (managed && legionMcpCount < 2)) return existing;
  const kept = [];
  let dropping = false;
  let inManagedBlock = false;
  for (const line of existing.split(/\r?\n/)) {
    if (line.includes(TOML_MANAGED_MARKER.HEADER_PREFIX)) inManagedBlock = true;
    if (line.includes(TOML_MANAGED_MARKER.HEADER_SUFFIX)) {
      inManagedBlock = false;
      dropping = false;
      kept.push(line);
      continue;
    }
    const header = /^\s*(\[[^\]]+\])/.exec(line)?.[1] ?? null;
    if (header) dropping = !inManagedBlock && (managed ? header === '[mcp_servers.legion]' : LEGACY_HEADERS.has(header));
    if (!dropping) kept.push(line);
  }
  return kept.join('\n').replace(/\n{3,}/g, '\n\n').replace(/\s+$/, '') + '\n';
}

function agentFileTarget(root, projection) {
  return {
    path: join(root, AGENTS_DIR, projection.file),
    kind: 'whole',
    reason: `install ${projection.name} agent projection under .codex/agents/`,
    content: agentToml(projection.name, sourceText(projection)),
  };
}

function configTarget(root) {
  const path = join(root, CONFIG_PATH);
  const raw = existsSync(path) ? readFileSync(path, 'utf8') : '';
  const existing = migrateLegacyConfig(raw);
  const inner = configInnerToml();
  const planned = upsertManagedBlock(existing, generatedHeader(), inner);
  const result = raw !== existing && planned.status === 'unchanged'
    ? { ...planned, status: 'replaced' }
    : planned;
  return { path, kind: 'toml-managed', reason: 'install Legion agent projections and MCP entry in .codex/config.toml', result };
}

export function detect(root) {
  return existsSync(join(root, 'AGENTS.md')) || existsSync(join(root, '.codex')) || existsSync(join(root, AGENTS_DIR));
}

export function targets(root) {
  return [...AGENT_PROJECTIONS.map((p) => agentFileTarget(root, p)), configTarget(root)];
}

export function plan(root) {
  return targets(root).map(({ path, reason }) => ({ path, reason }));
}

export function write(root) {
  const wrote = [];
  const managedConflicts = [];
  for (const target of targets(root)) {
    if (target.kind === 'whole') {
      writeIfDifferent(target.path, target.content);
      wrote.push(target.path);
    } else if (target.kind === 'toml-managed') {
      if (target.result.status === 'managed_conflict') {
        managedConflicts.push({ path: target.path, conflicts: target.result.conflicts });
        continue;
      }
      if (target.result.status === 'unchanged') continue;
      writeIfDifferent(target.path, target.result.content);
      wrote.push(target.path);
    }
  }
  return { wrote, wouldWrite: [], managedConflicts };
}

export function buildAgentToml(name, doctrineBody) {
  return agentToml(name, doctrineBody);
}
