import {executionReceipt,blocked} from './execution-receipt.mjs';
import {providerDependencies,scheduleProviders} from './scheduler.mjs';
import {executePlannedProvider} from '../providers/provider-executor.mjs';
import {normalizeProviderResult} from '../providers/sdk/result.mjs';

export class RunLedger {
  constructor({maxSteps=Infinity,maxCalls=Infinity,maxSpendMicros=Infinity,maxWallTimeMs=Infinity,clock=()=>Date.now()}={}){this.limits={maxSteps,maxCalls,maxSpendMicros,maxWallTimeMs};this.clock=clock;this.startedAt=clock();this.steps=0;this.calls=0;this.spendMicros=0;this.terminal=null;}
  reserve({steps=0,calls=0,spendMicros=0}={}){const next={steps:this.steps+steps,calls:this.calls+calls,spendMicros:this.spendMicros+spendMicros,wallTimeMs:this.clock()-this.startedAt};const breach=next.steps>this.limits.maxSteps?'step-limit':next.calls>this.limits.maxCalls?'call-limit':next.spendMicros>this.limits.maxSpendMicros?'spend-limit':next.wallTimeMs>this.limits.maxWallTimeMs?'wall-time-limit':null;if(breach){this.terminal={state:'STOPPED',reason:breach,...next};throw Object.assign(new Error(`run budget exceeded: ${breach}`),{code:'LEGION_RUN_BUDGET',receipt:this.terminal});}Object.assign(this,next);return Object.freeze({...next});}
  charge({spendMicros=0}={}){return this.reserve({spendMicros});}
  snapshot(){return Object.freeze({steps:this.steps,calls:this.calls,spendMicros:this.spendMicros,wallTimeMs:this.clock()-this.startedAt,terminal:this.terminal});}
}

export class RuntimeAdmission {
  constructor(){this.state='RUNNING';this.active=new Set();}
  admit(id){if(this.state!=='RUNNING')throw Object.assign(new Error('runtime is not accepting work'),{code:'LEGION_QUIESCING'});this.active.add(id);return()=>this.active.delete(id);}
  async quiesce({deadlineMs=0,cancel=async()=>{},hardKill=async()=>{},clock=()=>Date.now()}={}){this.state='QUIESCING';const started=clock();for(const id of [...this.active])await cancel(id);while(this.active.size&&clock()-started<deadlineMs)await new Promise((resolve)=>setTimeout(resolve,1));const forced=[...this.active];for(const id of forced){await hardKill(id);this.active.delete(id);}this.state='STOPPED';return Object.freeze({state:this.state,drained:forced.length===0,forced:forced.length});}
}

const denominator=(provider,plan)=>provider.denominator?.pathDigest??provider.denominatorDigest??plan.denominator?.pathDigest??null;
const normalizeProvider=(provider)=>({...provider,dependencies:providerDependencies(provider),resources:provider.execution?.resourceClaims??provider.resources??{},concurrencyKey:provider.execution?.concurrencyKey??provider.concurrencyKey??null});
function asReceipt(provider,result,plan,host){const binding=plan.binding??plan.repositoryBinding??null;const denominatorDigest=denominator(provider,plan);if(result?.kind==='legion-execution-result')return executionReceipt({...result,provider:provider.id,binding,denominatorDigest,providerResult:{...result.providerResult,coverage:{...(result.providerResult?.coverage??{}),denominatorDigest}}});const providerResult=normalizeProviderResult(provider,result);providerResult.coverage.denominatorDigest=denominatorDigest??providerResult.coverage.denominatorDigest;const now=host.clock.now();return executionReceipt({provider:provider.id,binding,denominatorDigest,command:{executable:null,args:[],cwd:plan.root},startedAt:now,completedAt:now,spawnStatus:'completed',tool:{status:'not-applicable',name:provider.runner?.module??provider.runner?.kind??'internal-module',version:provider.providerVersion??'1',probe:null,executableDigest:provider.runner?.moduleDigest??null},providerResult});}
export async function executePlan(plan,host){const receipts=[];const providers=(plan.providers??[]).map(normalizeProvider);const providerById=new Map(providers.map((provider)=>[provider.id,provider]));const terminal=new Map();const ceilings=plan.executionPolicy?.resourceCeilings??plan.config?.resources??null;const ledger=host.runLedger??new RunLedger({...plan.executionPolicy?.limits,clock:host.clock.now});const admission=host.runtimeAdmission??new RuntimeAdmission();for(const ids of scheduleProviders(providers,{mode:plan.schedule??'auto',concurrency:plan.config?.limits?.maxConcurrency??4,resources:ceilings})){for(const id of ids){const provider=providerById.get(id);const denominatorDigest=denominator(provider,plan);const blockedDependency=provider.dependencies.find((dependency)=>!terminal.get(dependency)?.providerResult?.complete);if(blockedDependency){const receipt=blocked({provider:id,binding:plan.binding,denominatorDigest},`dependency-not-complete:${blockedDependency}`);receipts.push(receipt);terminal.set(id,receipt);continue;}let release;try{release=admission.admit(id);ledger.reserve({steps:1,calls:1,spendMicros:Number(provider.execution?.reservedSpendMicros??0)});const result=await executePlannedProvider({provider,root:plan.root,plan,projection:plan.projection??plan.artifacts?.['blueprint-packet']??{},artifacts:new Map(Object.entries(plan.artifacts??{})),host});ledger.charge({spendMicros:Math.max(0,Number(result?.usage?.costMicros??0)-Number(provider.execution?.reservedSpendMicros??0))});const receipt=asReceipt(provider,result,plan,host);receipts.push(receipt);terminal.set(id,receipt);}catch(error){const receipt=blocked({provider:id,binding:plan.binding,denominatorDigest},`provider-execution-error:${error.message}`);receipts.push(receipt);terminal.set(id,receipt);if(typeof host.replan==='function')await host.replan({failedProvider:id,error:{code:error.code??null,message:error.message},completed:Object.fromEntries([...terminal].filter(([,value])=>value.providerResult?.complete)),remaining:providers.filter((candidate)=>!terminal.has(candidate.id))});}finally{release?.();}}}return{receipts,runLedger:ledger.snapshot(),runtimeState:admission.state};}
export function skippedReceipt(provider,reason){return blocked({provider:provider.id,denominatorDigest:provider.denominatorDigest??null},reason);}
