import { PROVIDER_ROLE, assertEnum, assertSchemaVersion } from '../../contracts/enums.mjs';
const REQUIRED=['id','providerVersion','family','lensIds','role','phase','dependsOn','consumes','produces','selector','denominatorKind','runner','hostCapabilities','execution','reasoning','benchmark','cleanClaim','controlIds','scopes','selectable'];
const PHASES=new Set(['inventory','source','runtime','product','release','facts','judgment','render']);
const RUNNERS=new Set(['planned','legacy-check','runtime-script','security-pack','external-process','imported-artifact','reasoning-contract','renderer']);
const EXECUTION_KEYS=new Set(['scheduleClass','resourceClaims','concurrencyKey','maxParallelism','orderSensitive','interruptible','cachePolicy','failurePolicy']);
const REASONING_KEYS=new Set(['requirement','trigger','subjectKind','freshContext','producerSeparation']);
const BENCHMARK_KEYS=new Set(['status','requiredForCleanClaim','qualificationDigest']);
export function validateProviderV2(provider){assertSchemaVersion('provider',provider.schemaVersion,[2]);for(const key of Object.keys(provider))if(!REQUIRED.includes(key)&&key!=='schemaVersion')throw new TypeError(`provider ${provider.id??'<unknown>'} unknown field ${key}`);for(const key of REQUIRED)if(provider[key]==null)throw new TypeError(`provider ${provider.id??'<unknown>'} missing ${key}`);assertEnum('provider role',PROVIDER_ROLE,provider.role);if(!PHASES.has(provider.phase))throw new TypeError(`provider ${provider.id} invalid phase`);if(!RUNNERS.has(provider.runner?.kind))throw new TypeError(`provider ${provider.id} invalid runner`);for(const field of ['lensIds','dependsOn','consumes','produces','hostCapabilities','controlIds','scopes'])if(!Array.isArray(provider[field]))throw new TypeError(`provider ${provider.id} ${field} must be array`);for(const [name,amount]of Object.entries(provider.execution?.resourceClaims??{}))if(!Number.isFinite(amount)||amount<0)throw new TypeError(`provider ${provider.id} invalid resource ${name}`);for(const key of Object.keys(provider.execution??{}))if(!EXECUTION_KEYS.has(key))throw new TypeError(`provider ${provider.id} unknown execution field ${key}`);for(const key of Object.keys(provider.reasoning??{}))if(!REASONING_KEYS.has(key))throw new TypeError(`provider ${provider.id} unknown reasoning field ${key}`);for(const key of Object.keys(provider.benchmark??{}))if(!BENCHMARK_KEYS.has(key))throw new TypeError(`provider ${provider.id} unknown benchmark field ${key}`);if(provider.runner.kind==='runtime-script'&&(!provider.runner.module||!/^sha256:[a-f0-9]{64}$/.test(provider.runner.moduleDigest??'')))throw new TypeError(`provider ${provider.id} runtime module must be digest sealed`);if(provider.runner.kind==='planned'&&provider.selectable)throw new TypeError(`provider ${provider.id} planned provider must be unselectable`);if(provider.selectable&&(!provider.controlIds.length||!provider.scopes.length))throw new TypeError(`provider ${provider.id} selectable provider requires controls and scopes`);return provider;}
export function validateProviderOutputAuthority(provider,result){if(provider.role==='candidate-generator'&&(result.findings?.length??0)>0)throw new TypeError('candidate-generator cannot emit findings');return result;}
