import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import test from 'node:test';
const root = fileURLToPath(new URL('../..', import.meta.url));
test('Claude and Codex plugin manifests project Legion metadata', () => {
  const claude = JSON.parse(readFileSync(`${root}/.claude-plugin/plugin.json`)); const codex = JSON.parse(readFileSync(`${root}/.codex-plugin/plugin.json`)); const marketplace = JSON.parse(readFileSync(`${root}/.claude-plugin/marketplace.json`));
  assert.equal(claude.name, 'legion'); assert.equal(codex.name, 'legion'); assert.equal(codex.interface.displayName, 'Legion');
  assert.match(claude.description, /Legion orchestrates capability selection & authority attachment/);
  assert.match(claude.description, /Arcane shapes cognitive processing & response policy/);
  assert.match(claude.description, /Guard gates typed effects/);
  assert.doesNotMatch(claude.description, /Arcane (?:gates|hooks)/);
  assert.deepEqual(codex.interface.capabilities, ['Legion orchestration', 'Arcane cognitive policy', 'Covenant review']);
  assert.match(codex.description, /Legion selects capabilities/);
  assert.match(codex.description, /Arcane shapes cognitive processing/);
  assert.match(codex.description, /Guard enforcement is host-dependent/);
  assert.match(marketplace.plugins[0].description, /Arcane shapes cognitive processing & response policy/);
  assert.match(marketplace.plugins[0].description, /Guard gates typed effects/);
  assert.doesNotMatch(marketplace.plugins[0].description, /Arcane gates/);
});
