import assert from 'node:assert/strict'; import test from 'node:test'; import {mkdtempSync,readFileSync,writeFileSync,readdirSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';import{spawn}from'node:child_process';import{fileURLToPath}from'node:url';import{AuthorityBindingStore}from'../lib/authority-binding-store.mjs';
test('binding stores digests only and is idempotent',()=>{const s=new AuthorityBindingStore({root:mkdtempSync(join(tmpdir(),'abs-')),clock:()=> '2026-01-01T00:00:00.000Z'});const a=s.observe({adapter:'codex',sessionId:'raw',agentId:'raw-agent',agentType:'sage',eventId:'hev_0123456789ABCDEFGHJKMNPQ'});assert.equal(a.created,true);assert.equal(s.observe({adapter:'codex',sessionId:'raw',agentId:'raw-agent',agentType:'sage',eventId:'hev_0123456789ABCDEFGHJKMNPQ'}).created,false);assert.equal(s.observe({adapter:'codex',sessionId:'raw',agentType:'sage',eventId:'hev_0123456789ABCDEFGHJKMNPQ'}).reason,'missing-identity');});
test('maps authority roles, binds Legion only from session root, & refuses Covenant authority',()=>{const s=new AuthorityBindingStore({root:mkdtempSync(join(tmpdir(),'abs-'))});for(const [type,authority]of Object.entries({sage:'sage',alchemist:'alchemist',oracle:'oracle'}))assert.equal(s.observe({adapter:'codex',sessionId:type,agentId:type,agentType:type,eventId:'hev_0123456789ABCDEFGHJKMNPQ'}).record.authority,authority);assert.equal(s.observeLegionSession({adapter:'codex',sessionId:'root',eventId:'hev_0123456789ABCDEFGHJKMNPQ'}).record.authority,'legion');assert.equal(s.observe({adapter:'codex',sessionId:'x',agentId:'x',agentType:'legion',eventId:'hev_0123456789ABCDEFGHJKMNPQ'}).reason,'unsupported-agent-type');assert.equal(s.observe({adapter:'codex',sessionId:'x',agentId:'x',agentType:'covenant-seat',eventId:'hev_0123456789ABCDEFGHJKMNPQ'}).reason,'unsupported-agent-type');});
test('conflict preserves bytes and corrupt records fail closed',()=>{const root=mkdtempSync(join(tmpdir(),'abs-')),s=new AuthorityBindingStore({root});s.observe({adapter:'codex',sessionId:'x',agentId:'a',agentType:'sage',eventId:'hev_0123456789ABCDEFGHJKMNPQ'});const p=s.path('codex','x','a'),before=readFileSync(p,'utf8');assert.throws(()=>s.observe({adapter:'codex',sessionId:'x',agentId:'a',agentType:'oracle',eventId:'hev_0123456789ABCDEFGHJKMNPQ'}),e=>e.code==='ARC_BINDING_MISMATCH');assert.equal(readFileSync(p,'utf8'),before);writeFileSync(p,'{');assert.throws(()=>s.get({adapter:'codex',sessionId:'x',agentId:'a'}),e=>e.code==='ARC_STORE_CORRUPT');});
test('lifecycle provenance is immutable and stale replacement preserves bytes',()=>{const root=mkdtempSync(join(tmpdir(),'abs-')),s=new AuthorityBindingStore({root});s.observe({adapter:'codex',sessionId:'x',agentId:'a',agentType:'sage',eventId:'hev_0123456789ABCDEFGHJKMNPQ'});const p=s.path('codex','x','a'),before=readFileSync(p,'utf8');assert.throws(()=>s.observe({adapter:'codex',sessionId:'x',agentId:'a',agentType:'sage',eventId:'hev_0123456789ABCDEFGHJKMNR'}),e=>e.code==='ARC_BINDING_MISMATCH');assert.equal(readFileSync(p,'utf8'),before);});
test('assertion requires key and never accepts caller authority',()=>{const s=new AuthorityBindingStore({root:mkdtempSync(join(tmpdir(),'abs-'))});s.observe({adapter:'codex',sessionId:'x',agentId:'a',agentType:'sage',eventId:'hev_0123456789ABCDEFGHJKMNPQ'});assert.throws(()=>s.assertForTurn({adapter:'codex',sessionId:'x',agentId:'a',turnId:'t',authorityLedger:{},authority:'sage',keyId:'k'}),e=>e.code==='ARC_AUTHORITY_MODEL_CLAIMED');assert.throws(()=>s.assertForTurn({adapter:'codex',sessionId:'x',agentId:'a',turnId:'t',authorityLedger:{},keyId:null}),e=>e.code==='ARC_AUTH_KEY_UNAVAILABLE');});
test('32-child barrier creates one immutable binding without child errors',async()=>{const root=mkdtempSync(join(tmpdir(),'abs-race-')),worker=fileURLToPath(new URL('./fixtures/authority-binding-race-worker.mjs',import.meta.url));const children=Array.from({length:32},()=>spawn(process.execPath,[worker,root],{stdio:['pipe','pipe','ignore']}));await Promise.all(children.map(c=>new Promise(r=>c.stdout.once('data',r))));const out=await Promise.all(children.map(c=>new Promise(r=>{let s='';c.stdout.on('data',x=>s+=x);c.on('close',(code)=>r({code,lines:s.trim().split(/\r?\n/)}));c.stdin.end('start\n');})));assert.ok(out.every(x=>x.code===0));const rows=out.map(x=>JSON.parse(x.lines.at(-1)));assert.ok(rows.every(x=>x.created===true||x.created===false));assert.equal(rows.filter(x=>x.created).length,1);assert.equal(rows.filter(x=>x.created===false).length,31);assert.equal(readdirSync(root).length,1);const s=new AuthorityBindingStore({root});const p=s.path('codex','race-session','race-agent'),before=readFileSync(p,'utf8');assert.throws(()=>s.observe({adapter:'codex',sessionId:'race-session',agentId:'race-agent',agentType:'alchemist',eventId:'hev_0123456789ABCDEFGHJKMNPQ'}),e=>e.code==='ARC_BINDING_MISMATCH');assert.equal(readFileSync(p,'utf8'),before);assert.equal(s.get({adapter:'codex',sessionId:'race-session'}),null);});
test('repeated 32-child barriers never expose partial bindings', async () => {
  const worker = fileURLToPath(new URL('./fixtures/authority-binding-race-worker.mjs', import.meta.url));
  for (let round = 0; round < 5; round += 1) {
    const root = mkdtempSync(join(tmpdir(), `abs-race-repeat-${round}-`));
    const children = Array.from({ length: 32 }, () => spawn(process.execPath, [worker, root], { stdio: ['pipe', 'pipe', 'ignore'] }));
    await Promise.all(children.map((child) => new Promise((resolve) => child.stdout.once('data', resolve))));
    const out = await Promise.all(children.map((child) => new Promise((resolve) => {
      let text = '';
      child.stdout.on('data', (chunk) => { text += chunk; });
      child.on('close', (code) => resolve({ code, lines: text.trim().split(/\r?\n/) }));
      child.stdin.end('start\n');
    })));
    assert.ok(out.every((result) => result.code === 0));
    const rows = out.map((result) => JSON.parse(result.lines.at(-1)));
    assert.ok(rows.every((row) => row.created === true || row.created === false));
    assert.equal(rows.filter((row) => row.created).length, 1);
    assert.equal(rows.filter((row) => row.created === false).length, 31);
    assert.equal(readdirSync(root).length, 1);
  }
});
