import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import { digestValue } from '../lib/canonical.mjs';
import { consumeCurrentUserScopeAmendment, mintCurrentUserScopeAmendment, verifyCurrentUserScopeAmendment } from '../lib/current-user-scope-amendment.mjs';
import { HostEventLedger } from '../lib/host-event-ledger.mjs';
import { generateTestKeyRing } from '../lib/keys.mjs';
import { ReceiptStore } from '../lib/receipt-store.mjs';

const binding={runId:'run_0123456789ABCDEFGHJKMNPQRS',taskId:'T-1',contractId:'EC-777',contractVersion:1,contractDigest:'sha256:'+'a'.repeat(64)};
function setup(role='current-user'){const root=mkdtempSync(join(tmpdir(),'arcane-scope-')),keys=generateTestKeyRing(['k1']);let now=Date.parse('2026-08-15T12:00:00.000Z');const ledgerStore=new HostEventLedger({root:join(root,'events'),keyRing:keys,keyId:'k1',clock:()=>new Date(now).toISOString()}),payload={prompt:'AMEND AC-1 old-to-new'},hostEvent=ledgerStore.append({eventId:'prompt-1',adapter:'codex',eventType:'UserPromptSubmit',sessionId:'session-1',binding,sourceRevision:'abc123',observedAuthority:role,payload}),receiptStore=new ReceiptStore({root:join(root,'receipts')}),core={acceptanceId:'AC-1',oldAcceptanceFingerprint:digestValue({acceptance:'old'}),newAcceptanceFingerprint:digestValue({acceptance:'new'}),sourceSetDigest:digestValue({source:'abc123'}),integratedStateIdentity:digestValue({state:'frozen'})},input={...core,challengeToken:payload.prompt,hostEvent,hostEventPayload:payload},expected={...core,userPromptEventDigest:digestValue(hostEvent),challengeToken:payload.prompt};return{root,keys,ledgerStore,receiptStore,input,expected,get now(){return now},set now(value){now=value}}}
test('current signed user challenge mints & consumes exact frozen-acceptance amendment once',()=>{const s=setup();try{const deps={ledgerStore:s.ledgerStore,receiptStore:s.receiptStore,keyRing:s.keys,keyId:'k1',clock:()=>new Date(s.now).toISOString()};const record=mintCurrentUserScopeAmendment(s.input,deps);assert.equal(record.kind,'arcane-current-user-scope-amendment');const verified=verifyCurrentUserScopeAmendment(s.expected,{ledgerStore:s.ledgerStore,receiptStore:s.receiptStore,keyRing:s.keys,now:new Date(s.now)});assert.equal(verified.allowed,true);assert.equal(verified.detail.acceptanceId,'AC-1');assert.equal(consumeCurrentUserScopeAmendment(s.expected,{ledgerStore:s.ledgerStore,receiptStore:s.receiptStore,keyRing:s.keys,now:new Date(s.now)}).allowed,true);assert.equal(verifyCurrentUserScopeAmendment(s.expected,{ledgerStore:s.ledgerStore,receiptStore:s.receiptStore,keyRing:s.keys,now:new Date(s.now)}).code,'ARC_REPLAY_NONCE_SEEN')}finally{rmSync(s.root,{recursive:true,force:true})}});
test('reviewers, replay, source/state drift, & later events deny amendment authority',()=>{const s=setup();try{const deps={ledgerStore:s.ledgerStore,receiptStore:s.receiptStore,keyRing:s.keys,keyId:'k1',clock:()=>new Date(s.now).toISOString()};assert.equal(verifyCurrentUserScopeAmendment(s.expected,{ledgerStore:s.ledgerStore,receiptStore:s.receiptStore,keyRing:s.keys,now:new Date(s.now)}).detail.disposition,'OUT_OF_SCOPE');const reviewer=setup('oracle');assert.throws(()=>mintCurrentUserScopeAmendment(reviewer.input,{ledgerStore:reviewer.ledgerStore,receiptStore:reviewer.receiptStore,keyRing:reviewer.keys,keyId:'k1'}),error=>error.code==='ARC_AUTHORITY_NOT_ASSERTED');rmSync(reviewer.root,{recursive:true,force:true});mintCurrentUserScopeAmendment(s.input,deps);assert.throws(()=>mintCurrentUserScopeAmendment(s.input,deps),error=>error.code==='ARC_REPLAY_NONCE_SEEN');assert.equal(verifyCurrentUserScopeAmendment({...s.expected,sourceSetDigest:digestValue({source:'drift'})},{ledgerStore:s.ledgerStore,receiptStore:s.receiptStore,keyRing:s.keys,now:new Date(s.now)}).detail.disposition,'OUT_OF_SCOPE');s.ledgerStore.append({eventId:'agent-event',adapter:'codex',eventType:'PostToolUse',sessionId:'session-1',binding,observedAuthority:'sage',payload:{}});assert.equal(verifyCurrentUserScopeAmendment(s.expected,{ledgerStore:s.ledgerStore,receiptStore:s.receiptStore,keyRing:s.keys,now:new Date(s.now)}).code,'ARC_AUTHORITY_NOT_ASSERTED')}finally{rmSync(s.root,{recursive:true,force:true})}});
