import assert from 'node:assert/strict';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import { digestValue } from '../lib/canonical.mjs';
import { mintAssuranceRequest, mintAssuranceReceipt, verifyAssurance } from '../lib/high-risk-assurance.mjs';
import { HighRiskAssuranceStore } from '../lib/high-risk-assurance-store.mjs';

const expected = Object.freeze({ runId: 'run_01KZSHB5GTN2FPS045W0J3Q6CT', taskId: 'T-1', contractId: 'EC-603', contractVersion: 7, contractDigest: `sha256:${'a'.repeat(64)}`, sourceRevision: '7f4adfeeb8dec603c9e60ea820a7f21052eef102' });
const keyRing = { get(keyId) { if (keyId !== 'covenant') throw Object.assign(new Error('missing'), { code: 'ARC_AUTH_KEY_UNAVAILABLE' }); return { keyId, key: 'test-only-covenant-key', status: 'active' }; } };
const binding = { schemaVersion: 1, kind: 'arcane-authority-binding', adapter: 'codex', sessionIdDigest: 'opaque', agentIdDigest: 'opaque-agent', agentType: 'covenant-seat', authority: 'covenant', observedEventId: 'event', observedAt: '2026-08-12T00:00:00.000Z' };
const sageBinding = { ...binding, agentType: 'sage', authority: 'sage' };
const bindings = { findLatest({ adapter, sessionId, authority }) { if(adapter !== 'codex' || sessionId !== 'session-1') return null; return authority === 'covenant' ? binding : authority === 'sage' ? sageBinding : null; } };
function request(changes = {}) { const value={ schemaVersion: 1, kind: 'arcane-high-risk-assurance-request', ...expected, intentRestatement: 'repair stop handling', blastRadius: 'Arcane hooks only', whySafe: 'fail closed', invocationProofDigest:'sha256:'+'e'.repeat(64), binding:{adapter:'codex',sessionId:'session-1',bindingDigest:digestValue(sageBinding)},issuedAt:'2026-08-12T00:00:00.000Z',expiresAt:'2026-08-12T01:00:00.000Z',nonce:'sage-request-nonce-0001',...changes }; return mintAssuranceRequest(value,{keyRing,keyId:'covenant'}); }
function receipt(req = request(), changes = {}) { const value = { schemaVersion: 1, kind: 'arcane-high-risk-assurance-receipt', receiptId: 'assurance-1', requestDigest: digestValue(req), invocationProofDigest:'sha256:'+'f'.repeat(64), ...expected, binding: { adapter: 'codex', sessionId: 'session-1', bindingDigest: digestValue(binding) }, verdict: 'SUPPORTED', issuedAt: '2026-08-12T00:00:00.000Z', ...changes }; return mintAssuranceReceipt(value, { keyRing, keyId: 'covenant' }); }
function verify(req, signed, extra = {}) { return verifyAssurance({ request: req, receipt: signed, expected }, { keyRing, authorityBindingStore: bindings, now: new Date('2026-08-12T00:01:00.000Z'), ...extra }); }

test('EC603 assurance lifecycle verifies persisted artifacts & exact consumption idempotency', () => { const root=mkdtempSync(join(tmpdir(),'arcane-assurance-')); try { const store=new HighRiskAssuranceStore({root,clock:()=> '2026-08-12T00:00:00.000Z'}),req=request(),signed=receipt(req),requestDigest=store.appendRequest(req).digest,receiptDigest=store.appendReceipt(signed).digest; assert.equal(verify(store.getRequest(requestDigest),store.getReceipt(receiptDigest)).allowed,true); assert.equal(store.consume({receiptDigest,completionClaimDigest:'sha256:'+'c'.repeat(64)}).detail.idempotent,false); assert.equal(store.consume({receiptDigest,completionClaimDigest:'sha256:'+'c'.repeat(64)}).detail.idempotent,true); assert.equal(store.consume({receiptDigest,completionClaimDigest:'sha256:'+'d'.repeat(64)}).code,'ARC_REPLAY_NONCE_SEEN'); } finally { rmSync(root,{recursive:true,force:true}); } });
test('EC603 assurance negative matrix fails closed', () => { const req=request(), signed=receipt(req); for (const value of [{...signed,requestDigest:'sha256:'+'b'.repeat(64)},receipt(req,{runId:'run_other'}),{...signed,authentication:{...signed.authentication,mac:'0'.repeat(64)}},receipt(req,{issuedAt:'2020-01-01T00:00:00.000Z'}),receipt(req,{binding:{...signed.binding,bindingDigest:'sha256:'+'c'.repeat(64)}})]) assert.equal(verify(req,value).allowed,false); for(const bad of [{...req,authentication:{...req.authentication,mac:'0'.repeat(64)}},{...req,binding:{...req.binding,bindingDigest:'sha256:'+'d'.repeat(64)}},{...req,whySafe:'substituted'},{...req,expiresAt:'2020-01-01T00:00:00.000Z'}]) assert.equal(verify(bad,signed).allowed,false); });
