import { exactBinding, finalize, redact } from '../shared.mjs';
import { sanitizeProducedArtifact } from '../../../../lib/platform/artifact-sanitize.mjs';
import { WEB_PROTOCOLS } from '../journey-plan.mjs';

export async function executeWebProtocol({ binding = {}, protocol, adapter = {} } = {}) {
  const gaps = exactBinding(binding).gaps.map((key) => `binding-missing:${key}`);
  if (!protocol) gaps.push('protocol-missing');
  if (binding.environment === 'production') return finalize('nemesis-web-protocol-receipt', { status: 'blocked', terminal: true, binding, protocol, observedState: null, durableState: null, artifacts: [], coverageGaps: ['production-effect-forbidden'] });
  const plan = WEB_PROTOCOLS.find((row) => row.protocolId === protocol);
  if (!plan) return finalize('nemesis-web-protocol-receipt', { status: 'unproven', terminal: true, binding, protocol, observedState: null, durableState: null, artifacts: [], coverageGaps: [...gaps, 'protocol-unrecognized'].sort() });
  if (plan.applicable !== true) return finalize('nemesis-web-protocol-receipt', { status: 'unsupported', terminal: true, binding, protocol, observedState: null, durableState: null, artifacts: [], coverageGaps: [...gaps, 'protocol-not-applicable'].sort() });
  if (gaps.length) return finalize('nemesis-web-protocol-receipt', { status: 'unproven', terminal: true, binding, protocol, observedState: null, durableState: null, artifacts: [], coverageGaps: gaps.sort() });
  if (typeof adapter.execute !== 'function') return finalize('nemesis-web-protocol-receipt', { status: 'unproven', terminal: true, binding, protocol, observedState: null, durableState: null, artifacts: [], coverageGaps: [...gaps, 'protocol-adapter-missing'].sort() });
  try { const rawObserved = await adapter.execute({ binding, protocol }); const rawArtifacts = rawObserved?.artifacts; const processed = Array.isArray(rawArtifacts) ? rawArtifacts.map((artifact) => ({ ...sanitizeProducedArtifact(artifact), bound: Object.entries(binding).every(([key, value]) => artifact?.binding?.[key] === value) })) : []; if (rawArtifacts !== undefined && !Array.isArray(rawArtifacts) || processed.some((item) => !item.valid || !item.bound)) gaps.push('protocol-artifact-invalid'); if (processed.some((item) => item.sensitive)) gaps.push('protocol-artifact-sensitive'); const observed = redact({ ...rawObserved, artifacts: undefined }); if (observed?.observedState === undefined || observed?.observedState === null) gaps.push('observed-state-missing'); if (observed?.durableState === undefined || observed?.durableState === null) gaps.push('durable-state-missing'); const status = observed?.status ?? 'pass'; if (!['pass', 'fail', 'partial', 'unproven', 'blocked', 'error'].includes(status)) gaps.push(`protocol-status-${status}`); return finalize('nemesis-web-protocol-receipt', { status: gaps.length ? 'unproven' : status, terminal: true, binding, protocol, observedState: observed?.observedState ?? null, durableState: observed?.durableState ?? null, artifacts: processed.filter((item) => item.valid && item.bound).map((item) => item.artifact), coverageGaps: gaps.sort() }); }
  catch (error) { return finalize('nemesis-web-protocol-receipt', { status: 'error', terminal: true, binding, protocol, observedState: null, durableState: null, artifacts: [], errors: [{ name: error?.name ?? 'Error', message: redact(error?.message ?? String(error)) }], coverageGaps: ['protocol-exercise-error'] }); }
}
