//! Port of `skills/designer/engine/scripts/lib/is-generated.mjs`.
//!
//! Decide whether a file is "generated" (regenerated by a build step, unsafe
//! to write variants into) vs. "source" (safe to edit). Signals, in order:
//! 1. `git check-ignore` (gitignored ⇒ assumed generated).
//! 2. A generated-file header marker in the first 300 bytes.

use regex::RegexSet;
use std::fs::File;
use std::io::Read;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::sync::LazyLock;

const HEADER_SCAN_BYTES: usize = 300;

static HEADER_MARKERS: LazyLock<RegexSet> = LazyLock::new(|| {
    RegexSet::new([
        r"(?i)@generated\b",
        r"GENERATED\s+FILE",
        r"(?i)\bAUTO-?GENERATED\b",
        r"(?i)\bDO\s+NOT\s+EDIT\b",
    ])
    .expect("static header marker patterns are valid")
});

#[derive(Debug, Default, Clone)]
pub struct IsGeneratedOptions {
    /// Project root; defaults to the process's current directory (mirrors
    /// `options.cwd || process.cwd()`).
    pub cwd: Option<PathBuf>,
}

/// Mirrors `isGeneratedFile(filePath, options)`.
pub fn is_generated_file(file_path: &str, options: &IsGeneratedOptions) -> bool {
    let cwd = options
        .cwd
        .clone()
        .unwrap_or_else(|| std::env::current_dir().unwrap_or_default());
    let path = Path::new(file_path);
    let abs_path = if path.is_absolute() {
        path.to_path_buf()
    } else {
        cwd.join(path)
    };

    if is_git_ignored(&abs_path, &cwd) {
        return true;
    }
    has_generated_header(&abs_path)
}

fn is_git_ignored(abs_path: &Path, cwd: &Path) -> bool {
    // Exit 0 = ignored; exit 1 = not ignored; exit 128 = not a git repo or
    // other error. Only exit 0 counts as "known to be ignored" (mirrors the
    // JS try/catch which treats any non-zero exit as "not known to be
    // ignored").
    match Command::new("git")
        .arg("check-ignore")
        .arg("--quiet")
        .arg(abs_path)
        .current_dir(cwd)
        .status()
    {
        Ok(status) => status.success(),
        Err(_) => false,
    }
}

fn has_generated_header(abs_path: &Path) -> bool {
    let Ok(mut file) = File::open(abs_path) else {
        return false;
    };
    let mut buf = vec![0u8; HEADER_SCAN_BYTES];
    let bytes_read = match file.read(&mut buf) {
        Ok(n) => n,
        Err(_) => return false,
    };
    let head = String::from_utf8_lossy(&buf[..bytes_read]);
    HEADER_MARKERS.is_match(&head)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;
    use std::sync::atomic::{AtomicU64, Ordering};

    static COUNTER: AtomicU64 = AtomicU64::new(0);

    /// Minimal own-tempdir helper (avoids adding a dev-dependency): a
    /// per-test directory under `std::env::temp_dir()`, cleaned up on drop.
    struct TmpDir(PathBuf);
    impl TmpDir {
        fn new() -> Self {
            let n = COUNTER.fetch_add(1, Ordering::SeqCst);
            let path = std::env::temp_dir().join(format!(
                "p8-designer-is-generated-{}-{}",
                std::process::id(),
                n
            ));
            std::fs::create_dir_all(&path).unwrap();
            TmpDir(path)
        }
        fn path(&self) -> &Path {
            &self.0
        }
    }
    impl Drop for TmpDir {
        fn drop(&mut self) {
            let _ = std::fs::remove_dir_all(&self.0);
        }
    }

    fn tmp_file(name: &str, contents: &str) -> (TmpDir, PathBuf) {
        let dir = TmpDir::new();
        let path = dir.path().join(name);
        let mut f = File::create(&path).unwrap();
        f.write_all(contents.as_bytes()).unwrap();
        (dir, path)
    }

    #[test]
    fn detects_do_not_edit_header() {
        let (dir, path) = tmp_file("a.html", "<!-- DO NOT EDIT: generated -->\n<div></div>");
        let opts = IsGeneratedOptions {
            cwd: Some(dir.path().to_path_buf()),
        };
        assert!(is_generated_file(path.to_str().unwrap(), &opts));
    }

    #[test]
    fn detects_generated_marker() {
        let (dir, path) = tmp_file("b.js", "// @generated by tool\nconsole.log(1)");
        let opts = IsGeneratedOptions {
            cwd: Some(dir.path().to_path_buf()),
        };
        assert!(is_generated_file(path.to_str().unwrap(), &opts));
    }

    #[test]
    fn plain_source_file_is_not_generated() {
        let (dir, path) = tmp_file("c.html", "<div>hello world</div>");
        let opts = IsGeneratedOptions {
            cwd: Some(dir.path().to_path_buf()),
        };
        assert!(!is_generated_file(path.to_str().unwrap(), &opts));
    }

    #[test]
    fn missing_file_is_not_generated() {
        let dir = TmpDir::new();
        let opts = IsGeneratedOptions {
            cwd: Some(dir.path().to_path_buf()),
        };
        assert!(!is_generated_file("does-not-exist.html", &opts));
    }
}
