import { digest } from '../../core/binding.mjs';
import { matchesSelector } from './selectors.mjs';
import { selectionTrace } from './trace.mjs';

const CONTRACT_KEYS=['version','selector','denominator','evidence','families','lenses','claimLevels','missingEvidenceEffect','decisionMode','providers','rules','scenarios','stopShip','provenance','benchmark','remediationOwner','sourceConcepts','unimplemented'];
const canonical=(value)=>JSON.stringify(value,(_,item)=>item&&typeof item==='object'&&!Array.isArray(item)?Object.fromEntries(Object.entries(item).sort(([a],[b])=>a.localeCompare(b))):item);
const compatible=(left,right)=>CONTRACT_KEYS.every((key)=>canonical(left[key]??null)===canonical(right[key]??null));
export function compileBaseline({ packs = [], portfolio, components, stacks = [], contract = {}, binding = null }) {
  const packIds=new Set(packs.map(({id})=>id));if(packIds.size!==packs.length)throw new Error('duplicate control pack ID');for(const pack of packs)for(const dependency of pack.dependencies??[])if(!packIds.has(dependency))throw new Error(`missing pack dependency: ${pack.id}:${dependency}`);
  const dependencies=new Map(packs.map((pack)=>[pack.id,pack.dependencies??[]]));const visiting=new Set(),visited=new Set();const visit=(id)=>{if(visiting.has(id))throw new Error(`control pack dependency cycle: ${id}`);if(visited.has(id))return;visiting.add(id);for(const dependency of dependencies.get(id)??[])visit(dependency);visiting.delete(id);visited.add(id);};for(const id of packIds)visit(id);
  const definitions=new Map();for(const pack of packs)for(const control of pack.controls??[]){const prior=definitions.get(control.id);if(prior&&!compatible(prior,control))throw new Error(`incompatible duplicate control: ${control.id}`);definitions.set(control.id,prior??control);}
  const selected=new Map();const traces=[];const targets=portfolio.targets??[];const targetById=new Map(targets.map((target)=>[target.id,target]));const contexts=[...targets.map((target)=>({subject:target,target,component:null})),...(components.components??[]).flatMap((component)=>(component.targetIds??[]).map((id)=>targetById.has(id)?{subject:component,target:targetById.get(id),component}:null).filter(Boolean))];
  for(const pack of [...packs].sort((a,b)=>a.id.localeCompare(b.id)))for(const control of pack.controls??[])for(const {subject,target,component} of contexts){const yes=matchesSelector(control.selector,{target,component,stacks,contract:{...(contract.observed??{}),...(contract.declared??{}),...contract}});traces.push({...selectionTrace(control,subject,yes),targetId:target.id});if(!yes)continue;const entry=selected.get(control.id)??{...control,targetIds:[],componentIds:[],packIds:[]};entry.targetIds.push(target.id);if(component)entry.componentIds.push(component.id);entry.packIds.push(pack.id);selected.set(control.id,entry);}
  const controls=[...selected.values()].map((control)=>({...control,targetIds:[...new Set(control.targetIds)].sort(),componentIds:[...new Set(control.componentIds)].sort(),packIds:[...new Set(control.packIds)].sort(),unimplemented:!(control.providers??[]).length})).sort((a,b)=>a.id.localeCompare(b.id));const denominator=controls.map(({id})=>id);const value={schemaVersion:1,kind:'legion-control-baseline',controls,traces:traces.sort((a,b)=>canonical(a).localeCompare(canonical(b))),binding,denominator,unimplemented:controls.filter(({unimplemented})=>unimplemented).map(({id})=>id)};return{...value,digest:digest(value)};
}
