import {executionReceipt,blocked} from './execution-receipt.mjs';
import {providerDependencies,scheduleProviders} from './scheduler.mjs';
import {executePlannedProvider} from '../providers/provider-executor.mjs';
import {normalizeProviderResult} from '../providers/sdk/result.mjs';

const denominator=(provider,plan)=>provider.denominator?.pathDigest??provider.denominatorDigest??plan.denominator?.pathDigest??null;
const normalizeProvider=(provider)=>({...provider,dependencies:providerDependencies(provider),resources:provider.execution?.resourceClaims??provider.resources??{},concurrencyKey:provider.execution?.concurrencyKey??provider.concurrencyKey??null});
function asReceipt(provider,result,plan,host){const binding=plan.binding??plan.repositoryBinding??null;const denominatorDigest=denominator(provider,plan);if(result?.kind==='legion-execution-result')return executionReceipt({...result,provider:provider.id,binding,denominatorDigest,providerResult:{...result.providerResult,coverage:{...(result.providerResult?.coverage??{}),denominatorDigest}}});const providerResult=normalizeProviderResult(provider,result);providerResult.coverage.denominatorDigest=denominatorDigest??providerResult.coverage.denominatorDigest;const now=host.clock.now();return executionReceipt({provider:provider.id,binding,denominatorDigest,command:{executable:null,args:[],cwd:plan.root},startedAt:now,completedAt:now,spawnStatus:'completed',tool:{status:'not-applicable',name:provider.runner?.module??provider.runner?.kind??'internal-module',version:provider.providerVersion??'1',probe:null,executableDigest:provider.runner?.moduleDigest??null},providerResult});}
export async function executePlan(plan,host){const receipts=[];const providers=(plan.providers??[]).map(normalizeProvider);const providerById=new Map(providers.map((provider)=>[provider.id,provider]));const terminal=new Map();const ceilings=plan.executionPolicy?.resourceCeilings??plan.config?.resources??null;for(const ids of scheduleProviders(providers,{mode:plan.schedule??'auto',concurrency:plan.config?.limits?.maxConcurrency??4,resources:ceilings})){for(const id of ids){const provider=providerById.get(id);const denominatorDigest=denominator(provider,plan);const blockedDependency=provider.dependencies.find((dependency)=>!terminal.get(dependency)?.providerResult?.complete);if(blockedDependency){const receipt=blocked({provider:id,binding:plan.binding,denominatorDigest},`dependency-not-complete:${blockedDependency}`);receipts.push(receipt);terminal.set(id,receipt);continue;}try{const result=await executePlannedProvider({provider,root:plan.root,plan,projection:plan.projection??plan.artifacts?.['cortex-projection']??{},artifacts:new Map(Object.entries(plan.artifacts??{})),host});const receipt=asReceipt(provider,result,plan,host);receipts.push(receipt);terminal.set(id,receipt);}catch(error){const receipt=blocked({provider:id,binding:plan.binding,denominatorDigest},`provider-execution-error:${error.message}`);receipts.push(receipt);terminal.set(id,receipt);}}}return{receipts};}
export function skippedReceipt(provider,reason){return blocked({provider:provider.id,denominatorDigest:provider.denominatorDigest??null},reason);}
