import assert from 'node:assert/strict';
import test from 'node:test';
import { createReleaseCandidate, verifyCandidateArtifact } from '../../lib/platform/release-candidate.mjs';
import { runJourney } from '../../lib/platform/journeys/runner.mjs';
import { runLifecycleAction } from '../../lib/platform/lifecycle/actions.mjs';
import { compileDesignerAuditProfile } from '../../lib/design/skill-compiler.mjs';
import { extractVisibleContent } from '../../lib/content/extract.mjs';
import { sourceSliceQualification } from '../../lib/qualification/source-slice.mjs';
import { buildSurfaceInventory } from '../../lib/design/surfaces.mjs';
import { createContentInventory } from '../../lib/content/inventory.mjs';
import { createTextLock, verifyTextLock } from '../../lib/content/text-lock.mjs';
import { analyzeContrast } from '../../providers/accessibility/contrast.mjs';
import { copyFacts } from '../../providers/copy/core.mjs';
import { assessDiscoverability } from '../../providers/discoverability/core.mjs';

test('release candidate binds runtime artifact bytes', () => { const candidate = createReleaseCandidate({ artifacts: [{ path: 'app.dmg', digest: 'sha256:abc' }] }); assert.equal(verifyCandidateArtifact(candidate, { path: 'app.dmg', digest: 'sha256:abc' }).status, 'pass'); assert.equal(verifyCandidateArtifact(candidate, { path: 'app.dmg', digest: 'sha256:def' }).status, 'fail'); });
test('journey records terminal blocked receipt when host is unavailable', async () => { const receipt = await runJourney({ scenario: { id: 'j', targetId: 't' }, capability: { status: 'unavailable' }, adapter: {} }); assert.equal(receipt.terminal, true); assert.equal(receipt.status, 'blocked'); });
test('lifecycle records a bound blocked receipt when destructive capability is missing', async () => { const receipt = await runLifecycleAction({ action: 'update', targetId: 't', capability: { status: 'available', destructiveActionsAllowed: false }, destructive: true }); assert.equal(receipt.status, 'blocked'); assert.deepEqual(receipt.coverageGaps, ['destructive-action-forbidden']); });
test('designer compiler retains audit rules & excludes authoring directives', () => { const profile = compileDesignerAuditProfile({ entries: [{ id: 'hierarchy', text: 'Review visual hierarchy.' }, { id: 'author', text: 'Edit page colors.' }] }); assert.equal(profile.rules.length, 1); assert.equal(profile.exclusions[0].reason, 'authoring-instruction-excluded'); });
test('content extraction stays artifact scoped & source qualification accounts every task', () => { const inventory = extractVisibleContent({ artifacts: [{ path: 'src/App.tsx', text: '<button aria-label="Save">Save</button>' }] }); assert.equal(inventory.items.length, 2); const receipt = sourceSliceQualification({ book: 9, expectedTaskCount: 1, tasks: [{ id: 'B9-001', status: 'implemented', mapping: 'unit' }] }); assert.equal(receipt.decision, 'SOURCE_COMPLETE'); });
test('surface & content identities remain stable for same input', () => { const inventory = buildSurfaceInventory({ artifacts: [{ file: 'src/A.tsx', route: '/a' }] }); assert.equal(inventory.surfaces.length, 1); const content = createContentInventory({ items: [{ text: 'Save', source: { file: 'src/A.tsx' }, surface: { type: 'button' } }] }); const lock = createTextLock({ contentId: content.items[0].id, text: 'Save', approver: 'a', reason: 'approved', approvedAt: '2026-08-08' }); assert.equal(verifyTextLock(lock, 'Save').status, 'pass'); assert.equal(verifyTextLock(lock, 'Delete').status, 'reopened'); });
test('content & discoverability providers preserve objective gaps', () => { assert.equal(analyzeContrast([{ foreground: '#777777', background: '#ffffff' }]).findings.length, 1); assert.equal(copyFacts([{ id: 'x', text: '{{name}}', surface: { type: 'button' } }]).findings.length, 1); assert.equal(assessDiscoverability({ pages: [{ id: 'home', indexable: true }] }).status, 'candidates'); });
