[package]
name = "legion-rules"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
legion-contracts = { path = "../legion-contracts" }
legion-policy-model = { path = "../legion-policy-model" }
legion-provider-sdk = { path = "../legion-provider-sdk" }
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
