import { parseArgs } from 'node:util';
import { readFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { EXIT, LegionError } from '../../errors.mjs';
import { loadHostKeyRing } from '../../../packages/arcane/lib/keys.mjs';
import { digestValue } from '../../../packages/arcane/lib/canonical.mjs';
import { mintAssuranceRequest, mintAssuranceReceipt } from '../../../packages/arcane/lib/high-risk-assurance.mjs';
import { verifyRecord } from '../../../packages/arcane/lib/receipt-auth.mjs';
import { AUTHORITY_PROOF_FIELDS } from '../../../packages/arcane/lib/authority-invocation-proof.mjs';
import { SessionBindingStore } from '../../../packages/arcane/lib/session-binding.mjs';
import { ContractSealStore } from '../../../packages/arcane/lib/contract-seal-store.mjs';
import { HostEventLedger } from '../../../packages/arcane/lib/host-event-ledger.mjs';
import { AuthorityInvocationProofIssuer } from '../../../packages/arcane/lib/authority-invocation-proof.mjs';
import { HighRiskAssuranceStore } from '../../../packages/arcane/lib/high-risk-assurance-store.mjs';
const session=(v,e)=>v||e.CODEX_THREAD_ID||e.CLAUDE_CODE_SESSION_ID||e.CLAUDE_SESSION_ID||e.CODEX_SESSION_ID||null;
const read=f=>JSON.parse(readFileSync(f,'utf8'));
const err=(m,c='ARC_CLAIM_PREREQUISITE_UNMET')=>{throw new LegionError(m,{code:c,exitCode:EXIT.INCOMPLETE});};
function verifyProofPair(ctx,request,receipt){const sage=ctx.issuer.findByDigest(request.invocationProofDigest),covenant=ctx.issuer.findByDigest(receipt.invocationProofDigest);for(const [proof,role,purpose] of [[sage,'sage','assurance-request'],[covenant,'covenant','assurance-countersign']]){if(!proof||proof.role!==role||proof.purpose!==purpose||!verifyRecord(proof,proof.authentication,{keyRing:ctx.keyRing,boundFields:AUTHORITY_PROOF_FIELDS,macDomain:`arcane-authority-proof:v1:${role}:${purpose}`}).allowed) return false;for(const f of ['sessionId','runId','taskId','contractId','contractVersion','contractDigest','sourceRevision'])if(proof[f]!==((f==='sessionId')?ctx.sessionId:(f==='sourceRevision'?ctx.seal.sourceRevision:ctx.binding[f])))return false;}return sage.invocationId!==covenant.invocationId&&sage.eventDigest!==covenant.eventDigest;}
function setup(values,env,cwd){const sessionId=session(values.session,env);if(!sessionId)err('ARC_SESSION_UNKNOWN','ARC_SESSION_UNKNOWN');const keyRing=loadHostKeyRing({dir:values['key-dir']||env.ARCANE_KEY_DIR||join(homedir(),'.claude','arcane-keys')});const binding=new SessionBindingStore({root:join(cwd,'.audit','arcane','session-bindings')}).getBinding(sessionId);if(!binding?.contractId||!binding.taskId)err('ARC_NO_CONTRACT: active bound run required','ARC_NO_CONTRACT');const seal=new ContractSealStore({root:join(cwd,'.audit','arcane','contract-seals')}).get(binding.contractId,binding.contractVersion);if(!seal||seal.contractDigest!==binding.contractDigest)err('ARC_CONTRACT_VERSION_MISMATCH');const ledger=new HostEventLedger({root:join(cwd,'.audit','arcane','host-events'),keyRing,keyId:keyRing.activeKeyId()});if(!ledger.verify().allowed)err('ARC_STORE_CORRUPT: inspect host events','ARC_STORE_CORRUPT');const current=ledger.records().reverse().find(e=>e.sessionId===sessionId);if(!current)err('ARC_CLAIM_PREREQUISITE_UNMET: current authenticated host event required');const issuer=new AuthorityInvocationProofIssuer({root:join(cwd,'.audit','arcane','authority-invocations'),keyRing,keyId:keyRing.activeKeyId(),ledgerStore:ledger});return{sessionId,keyRing,binding:{...binding,sessionId},seal,current,issuer,store:new HighRiskAssuranceStore({root:join(cwd,'.audit','arcane','high-risk-assurance')})};}
export async function runAssurance(argv,{stdout,env,cwd}){const [sub,...rest]=argv;if(sub==='--help'||sub==='help'){stdout.write('Usage: legion assurance request --file <risk.json> [--session <id>]\n       legion assurance countersign --request <request.json> [--file <receipt.json>] [--session <id>]\n       legion assurance inspect --receipt <digest> [--session <id>]\n       legion assurance consume --receipt <digest> --claim <digest> [--session <id>]\n');return{exitCode:EXIT.PASS};}let values;try{values=parseArgs({args:rest,strict:true,options:{file:{type:'string'},request:{type:'string'},receipt:{type:'string'},claim:{type:'string'},session:{type:'string'},'key-dir':{type:'string'}}}).values;}catch(e){throw new LegionError(e.message,{code:'USAGE',exitCode:EXIT.USAGE});}const ctx=setup(values,env,cwd);
 if(sub==='request'){if(!values.file)err('assurance request requires --file','USAGE');if(ctx.current.observedAuthority!=='sage')err('ARC_AUTHORITY_NOT_ASSERTED: current Sage event required','ARC_AUTHORITY_NOT_ASSERTED');const proof=ctx.issuer.issue({ledger:ctx.current,binding:ctx.binding,purpose:'assurance-request',role:'sage'}).proof,fields=read(values.file);const request=mintAssuranceRequest({schemaVersion:1,kind:'arcane-high-risk-assurance-request',runId:ctx.binding.runId,taskId:ctx.binding.taskId,contractId:ctx.binding.contractId,contractVersion:ctx.binding.contractVersion,contractDigest:ctx.binding.contractDigest,sourceRevision:ctx.seal.sourceRevision,intentRestatement:fields.intentRestatement,blastRadius:fields.blastRadius,whySafe:fields.whySafe,invocationProofDigest:digestValue(proof),binding:{adapter:ctx.current.adapter,sessionId:ctx.sessionId,bindingDigest:digestValue(ctx.current)},issuedAt:new Date().toISOString(),expiresAt:new Date(Date.now()+300000).toISOString(),nonce:proof.nonce},{keyRing:ctx.keyRing,keyId:ctx.keyRing.activeKeyId()});ctx.issuer.consume(proof,{artifactDigest:digestValue(request)});const saved=ctx.store.appendRequest(request);stdout.write(JSON.stringify({request:saved.value,requestDigest:saved.digest})+'\n');return{exitCode:EXIT.PASS};}
 if(sub==='countersign'||sub==='sign'){if(!values.request)err('assurance countersign requires --request','USAGE');if(ctx.current.observedAuthority!=='covenant')err('ARC_AUTHORITY_NOT_ASSERTED: current Covenant event required','ARC_AUTHORITY_NOT_ASSERTED');const presented=read(values.request),request=ctx.store.getRequest(digestValue(presented));if(!request||digestValue(request)!==digestValue(presented))err('ARC_CLAIM_PREREQUISITE_UNMET: persisted Sage request required');const sageProof=ctx.issuer.findByDigest(request.invocationProofDigest);if(!sageProof||sageProof.role!=='sage'||sageProof.purpose!=='assurance-request'||!verifyRecord(sageProof,sageProof.authentication,{keyRing:ctx.keyRing,boundFields:AUTHORITY_PROOF_FIELDS,macDomain:'arcane-authority-proof:v1:sage:assurance-request'}).allowed)err('ARC_CLAIM_PREREQUISITE_UNMET: verified Sage proof required');const proof=ctx.issuer.issue({ledger:ctx.current,binding:ctx.binding,purpose:'assurance-countersign',role:'covenant'}).proof;const receipt=mintAssuranceReceipt({schemaVersion:1,kind:'arcane-high-risk-assurance-receipt',receiptId:digestValue({request: digestValue(request),proof:digestValue(proof)}),requestDigest:digestValue(request),invocationProofDigest:digestValue(proof),runId:ctx.binding.runId,taskId:ctx.binding.taskId,contractId:ctx.binding.contractId,contractVersion:ctx.binding.contractVersion,contractDigest:ctx.binding.contractDigest,sourceRevision:ctx.seal.sourceRevision,binding:{adapter:ctx.current.adapter,sessionId:ctx.sessionId,bindingDigest:digestValue(ctx.current)},verdict:'SUPPORTED',issuedAt:new Date().toISOString()},{keyRing:ctx.keyRing,keyId:ctx.keyRing.activeKeyId()});ctx.issuer.consume(proof,{artifactDigest:digestValue(receipt)});const saved=ctx.store.appendReceipt(receipt);stdout.write(JSON.stringify({receipt:saved.value,receiptDigest:saved.digest})+'\n');return{exitCode:EXIT.PASS};}
 if(sub==='inspect'){if(!values.receipt)err('assurance inspect requires --receipt','USAGE');const value=ctx.store.read(values.receipt);stdout.write(JSON.stringify({found:Boolean(value),receiptDigest:values.receipt,requestDigest:value?digestValue(value.request):null})+'\n');return{exitCode:value?EXIT.PASS:EXIT.INCOMPLETE};}
 if(sub==='consume'){if(!values.receipt||!values.claim)err('assurance consume requires --receipt & --claim','USAGE');const value=ctx.store.read(values.receipt);if(!value)err('ARC_CLAIM_PREREQUISITE_UNMET: persisted assurance receipt required');if(!verifyProofPair(ctx,value.request,value.receipt))err('ARC_CLAIM_PREREQUISITE_UNMET: distinct current Sage & Covenant proofs required');const result=ctx.store.consume({receiptDigest:values.receipt,completionClaimDigest:values.claim});if(!result.allowed)err(result.code);stdout.write(JSON.stringify(result.detail)+'\n');return{exitCode:EXIT.PASS};}
 throw new LegionError('assurance requires request|countersign|inspect|consume',{code:'USAGE',exitCode:EXIT.USAGE});}