[package]
name = "legion-policy"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
legion-contracts = { path = "../legion-contracts" }
legion-policy-model = { path = "../legion-policy-model" }
thiserror.workspace = true

[dev-dependencies]
proptest = "1.6.0"
serde_json.workspace = true
