[package]
name = "legion-policy"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde_json.workspace = true
regex.workspace = true
hex.workspace = true
sha2.workspace = true
serde.workspace = true
legion-contracts = { path = "../legion-contracts" }
legion-policy-model = { path = "../legion-policy-model" }
thiserror.workspace = true

[dev-dependencies]
proptest = "1.11.0"
serde_json.workspace = true
